version: '3.7'
services:
  broker:
    image: 'rabbitmq:3.8.0'
    restart: always
    networks: 
      - broker
  worker:
    build: './worker'
    volumes:
      - type: 'bind'
        source: './worker'
        target: '/usr/share/worker'
    networks:
      - broker
  data:
    image: 'minio/minio:latest'
  db:
    image: 'mysql:8.0.18'
  web:
    image: 'nginx:latest'
    volumes:
      - type: 'bind'
        source: './web_ui/html'
        target: '/usr/share/nginx/html'
      - type: 'bind'
        source: './web_ui/conf'
        target: '/usr/share/nginx/conf'
    ports:
      - 80:80
networks:
  broker: 
