version: '3.7'
services:
  broker:
    image: 'rabbitmq:3.8.0'
    restart: always
    networks: 
      - broker
    ports:
      - 6000:5672
    deploy:
      placement:
        constraints:
          - node.role == manager
  api:
    image: 'docker.pkg.github.com/novium/airfoil/api:1572271892'
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - broker
  worker:
    image: 'docker.pkg.github.com/novium/airfoil/worker:1571999994'
    labels:
      - "traefik.http.routers.web.rule=Host(`api.cloud.dev.novium.pw`)"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '1.0'
    networks:
      - broker
  data:
    image: 'minio/minio:latest'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.http.routers.data.rule=Host(`data.cloud.dev.novium.pw`)"
    networks:
      - broker
  db:
    image: 'mysql:8.0.18'
    environment:
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
  web:
    image: 'docker.pkg.github.com/novium/airfoil/web_ui:1572249176'
    labels:
      - "traefik.http.routers.web.rule=Host(`cloud.dev.novium.pw`)"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - broker
  proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - broker
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  broker: 

volumes:
  minio-data:
  mysql-data: