version: '3.7'
services:
  broker:
    image: 'rabbitmq:3.8.0'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=airfoil
      - RABBITMQ_DEFAULT_PASS=airfoil
      - RABBITMQ_DEFAULT_VHOST=airfoil
    networks: 
      - broker
    ports:
      - 6000:5672
    deploy:
      placement:
        constraints:
          - node.role == manager
  api:
    image: 'docker.pkg.github.com/novium/airfoil/api:1572548126'
    deploy:
      labels:
        - "traefik.http.routers.api.rule=Host(`api.cloud.dev.novium.pw`)"
        - "traefik.http.services.api-service.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == manager
    networks:
      - broker
  worker:
    image: 'docker.pkg.github.com/novium/airfoil/worker:1572548123'
    networks:
      - broker
    deploy:
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '1.0'
  data:
    image: 'minio/minio:latest'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    deploy:
      labels:
        - "traefik.http.routers.data.rule=Host(`data.cloud.dev.novium.pw`)"
        - "traefik.http.services.data-service.loadbalancer.server.port=9000"
      placement:
        constraints:
          - node.role == manager
    networks:
      - broker
  db:
    image: 'mysql:8.0.18'
    environment:
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - broker
  web:
    image: 'docker.pkg.github.com/novium/airfoil/web_ui:1572544586'
    deploy:
      labels:
        - "traefik.http.routers.web.rule=Host(`cloud.dev.novium.pw`)"
        - "traefik.http.services.web-service.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == manager
    networks:
      - broker
  proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker --providers.docker.swarmMode=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - broker
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  broker: 

volumes:
  minio-data:
  mysql-data: