version: '3.7'
services:
  broker:
    image: 'rabbitmq:3.8.0'
    restart: always
    networks: 
      - broker
  data:
    image: 'minio/minio:latest'
  db:
    image: 'mysql:8.0.18'
networks:
  broker:
