name: Build Worker Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd worker 
        docker login docker.pkg.github.com -u novium -p ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/novium/airfoil/worker:$(date +%s)
        docker push docker.pkg.github.com/novium/airfoil/worker:$(date +%s)
